In [7]:
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
import numpy as np
import os
os.chdir('D://user//User/pydata')
data = pd.read_csv('breast-cancer-wisconsin.csv', encoding='utf-8')
X=data[data.columns[1:10]]
X1=data.iloc[:,1:10]
y=data[['Class']]

In [8]:
X.head()

Clump_Thickness  Cell_Size  Cell_Shape  Marginal_Adhesion  \
0                5          1           1                  1   
1                5          4           4                  5   
2                3          1           1                  1   
3                6          8           8                  1   
4                4          1           1                  3   

   Single_Epithelial_Cell_Size  Bare_Nuclei  Bland_Chromatin  Normal_Nucleoli  \
0                            2            1                3                1   
1                            7           10                3                2   
2                            2            2                3                1   
3                            3            4                3                7   
4                            2            1                3                1   

   Mitoses  
0        1  
1        1  
2        1  
3        1  
4        1

In [9]:
X1.head()

Clump_Thickness  Cell_Size  Cell_Shape  Marginal_Adhesion  \
0                5          1           1                  1   
1                5          4           4                  5   
2                3          1           1                  1   
3                6          8           8                  1   
4                4          1           1                  3   

   Single_Epithelial_Cell_Size  Bare_Nuclei  Bland_Chromatin  Normal_Nucleoli  \
0                            2            1                3                1   
1                            7           10                3                2   
2                            2            2                3                1   
3                            3            4                3                7   
4                            2            1                3                1   

   Mitoses  
0        1  
1        1  
2        1  
3        1  
4        1

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, random_state=42, stratify=y)

In [11]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(X_train)
X_scaled_train = scaler.transform(X_train)
X_scaled_test = scaler.transform(X_test)

In [12]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_scaled_train, y_train)
pred_train = model.predict(X_scaled_train,)
model.score(X_scaled_train,y_train)

0.97265625

In [14]:
from sklearn.metrics import confusion_matrix
confusion_train = confusion_matrix(y_train, pred_train)
print(confusion_train)

[[328   5]
 [  9 170]]


In [16]:
from sklearn.metrics import classification_report
cfreport_train = classification_report(y_train, pred_train)
print(cfreport_train)

              precision    recall  f1-score   support

           0       0.97      0.98      0.98       333
           1       0.97      0.95      0.96       179

    accuracy                           0.97       512
   macro avg       0.97      0.97      0.97       512
weighted avg       0.97      0.97      0.97       512



In [17]:
pred_test = model.predict(X_scaled_test)
model.score(X_scaled_test, y_test)

0.9590643274853801

In [18]:
confusion_test = confusion_matrix(y_test, pred_test)
print(confusion_test)

[[106   5]
 [  2  58]]


In [20]:
from sklearn.metrics import classification_report
cfreport_test = classification_report(y_test, pred_test)
print(cfreport_test)

              precision    recall  f1-score   support

           0       0.98      0.95      0.97       111
           1       0.92      0.97      0.94        60

    accuracy                           0.96       171
   macro avg       0.95      0.96      0.96       171
weighted avg       0.96      0.96      0.96       171



In [21]:
params_grid = {'C':[0.001,0.01,0.1,1,10,100]}
from sklearn.model_selection import GridSearchCV
grid_search = GridSearchCV(LogisticRegression(), params_grid, cv=5)
grid_search.fit(X_scaled_train, y_train)

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [0.001, 0.01, 0.1, 1, 10, 100]})

In [22]:
print(grid_search.best_params_)

{'C': 10}


In [24]:
print(grid_search.best_score_)

0.972606129830573


In [26]:
print(grid_search.score(X_scaled_test, y_test))

0.9590643274853801


In [28]:
## Random Search
from scipy.stats import randint
param_distribs = {'C': randint(low=0.001, high = 100)}
from sklearn.model_selection import RandomizedSearchCV
random_search = RandomizedSearchCV(LogisticRegression(), param_distributions = param_distribs, n_iter=100, cv=5)
random_search.fit(X_scaled_train, y_train)


RandomizedSearchCV(cv=5, estimator=LogisticRegression(), n_iter=100,
                   param_distributions={'C': <scipy.stats._distn_infrastructure.rv_frozen object at 0x0000019847416670>})

In [29]:
print(random_search.best_params_)

{'C': 14}


In [30]:
print(random_search.best_score_)

0.9745478774033887


In [32]:
print(random_search.score(X_scaled_test, y_test))

0.9590643274853801


In [36]:
#KNN
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier()
model.fit(X_scaled_train , y_train)
pred_train= model.predict(X_scaled_train)
model.score(X_scaled_train, y_train)

0.984375

In [38]:
from sklearn.metrics import confusion_matrix
confusion_train = confusion_matrix(y_train, pred_train)
print(confusion_train)

[[331   2]
 [  6 173]]


In [42]:
from sklearn.metrics import classification_report
cfreport_train = classification_report(y_train, pred_train)
print(cfreport_train)

              precision    recall  f1-score   support

           0       0.98      0.99      0.99       333
           1       0.99      0.97      0.98       179

    accuracy                           0.98       512
   macro avg       0.99      0.98      0.98       512
weighted avg       0.98      0.98      0.98       512



In [43]:
pred_test=model.predict(X_scaled_test)
model.score(X_scaled_test, y_test)

0.9532163742690059

In [49]:
confusion_test = confusion_matrix(y_test, pred_test)
print(confusion_test)

[[106   5]
 [  3  57]]


In [50]:
from sklearn.metrics import classification_report
cfreport_test = classification_report(y_test, pred_test)
print(cfreport_test)

              precision    recall  f1-score   support

           0       0.97      0.95      0.96       111
           1       0.92      0.95      0.93        60

    accuracy                           0.95       171
   macro avg       0.95      0.95      0.95       171
weighted avg       0.95      0.95      0.95       171



In [51]:
param_grid = {'n_neighbors': [1,3,5,7,9,11]}
from sklearn.model_selection import GridSearchCV
grid_search=GridSearchCV(KNeighborsClassifier(), param_grid, cv=5)
grid_search.fit(X_scaled_train, y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': [1, 3, 5, 7, 9, 11]})

In [53]:
print(grid_search.best_params_)

{'n_neighbors': 3}


In [54]:
print(grid_search.best_score_)

0.9823910146582906


In [55]:
print(grid_search.score(X_scaled_test, y_test))

0.9532163742690059


## random Search

In [56]:
from scipy.stats import randint
param_distribs = {'n_neighbors': randint(low=1, high=20)}
from sklearn.model_selection import RandomizedSearchCV
random_search = RandomizedSearchCV(KNeighborsClassifier(), param_distributions=param_distribs,
                                  n_iter=20, cv=5)
random_search.fit(X_scaled_train,y_train)

RandomizedSearchCV(cv=5, estimator=KNeighborsClassifier(), n_iter=20,
                   param_distributions={'n_neighbors': <scipy.stats._distn_infrastructure.rv_frozen object at 0x0000019847530820>})

In [57]:
print(random_search.best_params_)

{'n_neighbors': 3}


In [58]:
print(random_search.best_score_)

0.9823910146582906


In [59]:
print(random_search.score(X_scaled_test, y_test))

0.9532163742690059


In [ ]:
#KNN은 심플하면서 직관적으로 활용할 수 있다. 