In [2]:
import os
import numpy as np 
import pandas as pd
os.chdir('D:/user/User/pydata')
data=pd.read_csv("house_price.csv", encoding='utf-8')

In [3]:
X=data.iloc[:,1:5]
#X = data[data.coumns[1:5]]
y=data[['house_value']]

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=42)


In [16]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(X_train)
X_scaled_train = scaler.transform(X_train)
X_scaled_test= scaler.transform(X_test)

In [14]:
from sklearn.neighbors import KNeighborsRegressor
model = KNeighborsRegressor()
model.fit(X_scaled_train,y_train)
pred_train = model.predict(X_scaled_train)
model.score(X_scaled_train, y_train)

0.6804607237174459

In [17]:
pred_test = model.predict(X_scaled_test)
model.score(X_scaled_test,y_test)

0.5541889571372401

In [20]:
## RMSE(Root Mean Squared Error)
from sklearn.metrics import mean_squared_error
Mse_train = mean_squared_error(y_train, pred_train)
Mse_test = mean_squared_error(y_test, pred_test)
print(np.sqrt(Mse_train))
print(np.sqrt(Mse_test))

53952.69804097723
63831.91662964773


## 분류(Classification)

In [23]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(X_scaled_train, y_train)
pred_train = model.predict(X_scaled_train)
model.score(X_scaled_train,y_train)

D:\user\User\CEO\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


0.10590984471581487

In [24]:
from sklearn.metrics import confusion_matrix
confusion_train = confusion_matrix(y_train, pred_train)
print(confusion_train)

[[1 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]]


In [26]:
from sklearn.metrics import classification_report
cfreport_train = classification_report(y_train, pred_train)
print(cfreport_train)

              precision    recall  f1-score   support

       14999       1.00      1.00      1.00         1
       17500       1.00      1.00      1.00         1
       22500       1.00      1.00      1.00         1
       26900       1.00      1.00      1.00         1
       27500       1.00      1.00      1.00         1
       30000       0.00      0.00      0.00         2
       32500       0.07      1.00      0.13         2
       32900       1.00      1.00      1.00         1
       33200       1.00      1.00      1.00         1
       34400       1.00      1.00      1.00         1
       34600       1.00      1.00      1.00         1
       36600       1.00      1.00      1.00         1
       36700       1.00      1.00      1.00         1
       37500       0.00      0.00      0.00         3
       37900       1.00      1.00      1.00         1
       38800       1.00      1.00      1.00         1
       39200       1.00      1.00      1.00         1
       39600       1.00    

D:\user\User\CEO\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\user\User\CEO\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\user\User\CEO\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
